name: Build DFClang

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: chmod build.sh
      run: sudo chmod +x build.sh
    - name: ./build.sh
      run: ./build.sh
